### PR TITLE
Add RBC tests

### PR DESCRIPTION
**Pull request by mattdlh**
Add RBC tests from https://github.com/xnd-project/rbc

### CODE REVIEW

**Comment by mattdlh** [comment]
retest this please

**Comment by mattdlh** [comment]
retest this please

**Comment by mattdlh** [comment]
retest this please

**Comment by mattdlh** [comment]
Tested and working in Jenkins.

NOTE: RBC tests are only functional with the CPU-only db as of right now

**Comment by mikehinchey** [comment]
@jclay should the rbc version be upgraded to 0.3.0?
https://github.com/omnisci/pymapd/blob/4a092d9fc409d4cb637bf1f52a82c0dc8fb98ade/setup.py#L21

**Comment by jclay** [comment]
@mikehinchey I will make that upgrade in a new PR.

**Pull request merged**
