### PR TITLE
Add black formatter and format files

### LINKED ISSUE #251: Add an auto code formatter with configurable parameters
Right now we have to format the code manually like `flake8` . We need to add an auto code formatter to make it clear and easy for the contributors to run configure their env and let the machine do the work of formatting.

### LINKED ISSUE #284: Use `omnisci/core-os-cpu:latest` instead of `mapd/core-os-cpu:latest` while running the tests
conftest.py:49 still pulls image from old `mapd/core-os-cpu`. It should be renamed to `omnisci/core-os-cpu:latest`

### PR DESCRIPTION
**Pull request by wamsiv**
fixes #251 
fixes #284

### CODE REVIEW

**Comment by randyzwitch** [comment]
Does this PR just trade Black for Flake, or will it auto-format code using Black when someone submits a PR?

**Comment by wamsiv** [comment]
@randyzwitch Black format check will be added along Flake checks and will not auto format code just like Flake.

**Comment by randyzwitch** [comment]
I'm not sure I see the value of a gigantic diff, just to switch linters. At least for Atom, there are both flake8 and Black auto-formatting plugins on save, so what do we gain by moving to Black?

**Comment by randyzwitch** [comment]
Closing this for now, fixed conftest issue. Will revisit Black once it's clearer how we can do this automatically

**Comment by xmnlab** [comment]
Ibis has `black` inside the git pre-commit hook and it uses also the pre-commit as a mechanism for checking inside CI. So it helps to send code in the desired format and the CI will check if the author used pre-commit. ibis has also other services inside pre-commit such as flake8 and isort.

maybe it could be helpful for `pymapd` now or in the future

**Pull request closed without merging**
