### PR TITLE
add check before closing connection

### PR DESCRIPTION
**Pull request by anmyachev**

### CODE REVIEW

**Comment by anmyachev** [comment]
@randyzwitch CI errors seem not from my changes, plz review

**Comment by randyzwitch** [comment]
I no longer work at the company, please find someone else to review your PR, possibly @andrewseidl

**Comment by anmyachev** [comment]
> I no longer work at the company, please find someone else to review your PR, possibly @andrewseidl

@andrewseidl can you do review?

**Comment by mikehinchey** [comment]
@anmyachev What problem is this change solving?  It seems okay to me.

(The tests are failing because the rbc library changed, not because of this code change.)

**Comment by mikehinchey** [comment]
@anmyachev see my PR #304

**Pull request merged**
