### PR TITLE
Add load table columnar geospatial

### LINKED ISSUE #319: Add support for `geospatial` data to `load_table` using `columnar` method

### PR DESCRIPTION
**Pull request by xmnlab**
This PR adds support for geospatial data ("POINT", "LINESTRING", "POLYGON", "MULTIPOLYGON").

It also add support for create_table for geospatial data.

resolves #319

### CODE REVIEW

**Comment by xmnlab** [comment]
@andrewseidl I am adding support for the geospatial data to auto table creation (when using load_table).

I am having an issue here related to the SQL transformation.

For example I have these row descriptions (from `omnisci.thrift.OmniSci.Client.send_create_table`:

```python
[
    TColumnType(col_name='a', col_type=TTypeInfo(type=13, encoding=None, nullable=None, is_array=None, precision=None, scale=None, comp_param=None, size=-1), is_reserved_keyword=None, src_name=None, is_system=None, is_physical=None, col_id=None), 
    TColumnType(col_name='b', col_type=TTypeInfo(type=14, encoding=None, nullable=None, is_array=None, precision=None, scale=None, comp_param=None, size=-1), is_reserved_keyword=None, src_name=None, is_system=None, is_physical=None, col_id=None), 
    TColumnType(col_name='c', col_type=TTypeInfo(type=15, encoding=None, nullable=None, is_array=None, precision=None, scale=None, comp_param=None, size=-1), is_reserved_keyword=None, src_name=None, is_system=None, is_physical=None, col_id=None), 
    TColumnType(col_name='d', col_type=TTypeInfo(type=16, encoding=None, nullable=None, is_array=None, precision=None, scale=None, comp_param=None, size=-1), is_reserved_keyword=None, src_name=None, is_system=None, is_physical=None, col_id=None), 
    TColumnType(col_name='e', col_type=TTypeInfo(type=2, encoding=None, nullable=None, is_array=None, precision=None, scale=None, comp_param=None, size=-1), is_reserved_keyword=None, src_name=None, is_system=None, is_physical=None, col_id=None), 
    TColumnType(col_name='f', col_type=TTypeInfo(type=6, encoding=4, nullable=None, is_array=None, precision=None, scale=None, comp_param=None, size=-1), is_reserved_keyword=None, src_name=None, is_system=None, is_physical=None, col_id=None), 
    TColumnType(col_name='g', col_type=TTypeInfo(type=5, encoding=None, nullable=None, is_array=None, precision=None, scale=None, comp_param=None, size=-1), is_reserved_keyword=None, src_name=None, is_system=None, is_physical=None, col_id=None)
]```

and for some reason it is translated to:

```
CREATE TABLE myautotableageo (a NULL(POINT), b NULL(LINESTRING), c NULL(POLYGON), d NULL(MULTIPOLYGON), e BIGINT, f TEXT ENCODING DICT(0), g DOUBLE);
```

and this `NULL` is unexpected ... if I remove manually `NULL()` it works

do you have any suggestion about where I could check to fix that? thanks!!

**Comment by xmnlab** [comment]
it looks it is related to https://github.com/omnisci/omniscidb/blob/v5.2.2/Shared/sqltypes.h#L358
probably it should be define as described here: https://docs.omnisci.com/latest/5_datatypes.html#geospatial (e.g. 'GEOMETRY(POINT)')

I am taking a look how to specify the subtype

**Comment by xmnlab** [comment]
this PR is ready for review! thanks!

**Comment by xmnlab** [comment]
note: maybe would be good to add some documentation about the new geospatial lib dependencies

**Comment by xmnlab** [comment]
@jp-harvey @andrewseidl this PR is ready for review. thanks!

**Comment by andrewseidl** [comment]
@xmnlab could you rebase? Doesn't look like I have write access to the pr branch.

Looks good otherwise, I have a rebased branch at https://github.com/omnisci/pymapd/tree/add-load-table-columnar-geospatial

**Pull request merged**
