### PR TITLE
adding the ability to get a single dashboard object

### PR DESCRIPTION
**Pull request by Zeerg**

### CODE REVIEW

**Comment by randyzwitch** [comment]
Is there a reasonable way to add a test to this? Maybe by re-using this code somehow? 

https://github.com/omnisci/pymapd/blob/master/tests/data/dashboard_metadata.py

If you `create_dashboard`, I believe the method returns the dashboard_id, which then you could pass into your new method just to prove it works.

**Comment by Zeerg** [comment]
https://github.com/omnisci/pymapd/blob/master/tests/test_integration.py#L387 tests the underlying logic already.

**Comment by randyzwitch** [comment]
Agreed. Can you change that test to use the public method?

**Comment by Zeerg** [comment]
Good call. Done

**Pull request merged**
