### PR TITLE
Switch Docker reference to OmniSci

### PR DESCRIPTION
**Pull request by randyzwitch**
Switch Docker reference to the newer OmniSci account, since presumably the mapd Docker Hub will eventually stop getting updated

### CODE REVIEW

**Comment by randyzwitch** [comment]
Not sure how this is possible, to pass on one but not the other. Even restarted it, got same result.

**Comment by wamsiv** [comment]
Could you try once with `v4.6.0` mentioned as a tag instead of latest, just wanted to make sure it is on the latest build.

**Comment by andrewseidl** [comment]
Try rebasing your branch over master

**Comment by wamsiv** [comment]
Yes 56016c61022899cddeef891edef638609f65d343 is not picked in your branch.

**Comment by wamsiv** [comment]
:tada: . Please change the tag back to `latest` :)

**Comment by randyzwitch** [comment]
There it is, @andrewseidl my version control hero

**Pull request merged**
