### PR TITLE
Remove geopandas as a run dependency

### LINKED ISSUE #330: Remove geospatial libraries as depencies
After adding the geospatial libraries dependencies, conda environment solving increased from < 1 min to > 10 mins.

from @jclay :

> ... if Ibis is the primary consumer, it will bring along geopandas by default. Perhaps we can throw a runtime error here 
> https://github.com/omnisci/pymapd/blob/master/pymapd/_pandas_loaders.py#L260 to let the user know geopandas is required if > they attempt to load a GeoDataFrame

so maybe it would be good to remove the gespatial library dependencies.

### PR DESCRIPTION
**Pull request by xmnlab**
This PR resolves #330

as it looks like geopandas dependency increased the conda resolving time considerably, this PR removes geopandas from run dependency.

### CODE REVIEW

**Comment by xmnlab** [comment]
this PR is ready for review. thanks!

**Comment by xmnlab** [comment]
@jclay .. sounds good. I will do it. thanks!

**Comment by jclay** [comment]
Thanks @xmnlab looks good!

We will want to keep an eye on the `libtiff=4.0.10` pin as well. As soon as that build issue affecting libtiff is fixed, we will likely see some benefit from relaxing that as well.

**Comment by xmnlab** [comment]
sounds good. I opened an issue for that: https://github.com/omnisci/pymapd/issues/334

**Pull request merged**
