### PR TITLE
Update pinning

### PR DESCRIPTION
**Pull request by xmnlab**
This PR updates the pinnings and updates CI.

### CODE REVIEW

**Comment by xmnlab** [comment]
this PR is ready for review. thanks!

**Comment by jclay** [comment]
Hi @xmnlab thanks for the PR. Are you able to allow commits or resolve the merge conflict? I have resolved the master conflict, just need to make sure we keep the RBC tests that were recently added. The git patch resolution tries to combine the pipelines in the Jenkinsfile. See my branch here for how I resolved it: https://github.com/omnisci/pymapd/blob/jclay/update-pinning/Jenkinsfile

**Comment by xmnlab** [comment]
@jclay thanks for reviewing that. I added your code there, thank you so much.

maybe this PR is a bit old .. I saw that the team was changing the code related to pinning, not sure if this PR still has some value. let me know if I can fix or improve anything here. thanks!

PS: I tried to allow maintainers edits the branch, but I didn't find the option, sorry :(

**Comment by andrewseidl** [comment]
@mapd-bot-os retest this please

**Comment by xmnlab** [comment]
for some reason, I am not seeing the CI here. is it just for me? if not, should I open a new PR?

**Comment by jclay** [comment]
@xmnlab we are troubleshooting an issue where the CI fails to run on forks of the repo.

**Comment by xmnlab** [comment]
is there anything I can do? if this PR is still important and if you want to, feel free to push that to a branch here.

**Comment by xmnlab** [comment]
PS: just to clarify, I don't mind waiting for the CI too :)

**Comment by jclay** [comment]
Closing this in favor of the new PR ^

**Pull request closed without merging**
