### PR TITLE
dev/test options for port

### PR DESCRIPTION
**Pull request by mikehinchey**
Add Makefile for common commands

Allow custom ports for test DB

fix ci/install-test-deps-conda.sh: quote versions to avoid shell redirection

### CODE REVIEW

**Comment by randyzwitch** [comment]
As mentioned in our call Mike, I'm conceptually on-board with this once the tests pass. Please add a section into the docs (probably [here](https://github.com/omnisci/pymapd/blob/master/docs/source/contributing.rst) highlighting the different makefile commands)

**Comment by mikehinchey** [comment]
Retest this please.

**Comment by mikehinchey** [comment]
@andrewseidl I did add a mechanism in the makefile to specify PYTHON version. I know work has moved to pyomnisci, but I needed to work on a change for pymapd this week, so I revived this PR.

**Comment by jclay** [comment]
Closing since this is tale.

**Pull request closed without merging**
